package ro.pahotech.rwid.tableConditions;

import static ro.pahotech.rwid.Data.properties;

public class TableConditionsData {
    static final String LABEL_GUST = "LABEL_GUST";
    static final String LOWER_BOUND_C2LHPV_EBOR = "LOWER_BOUND_C2LHPV_EBOR";
    static final String LOWER_BOUND_STRONG_WIND_50 = "LOWER_BOUND_STRONG_WIND_50";
    static final String LOWER_BOUND_STRONG_WIND = "LOWER_BOUND_STRONG_WIND";
    static final String MESSAGE_C2LHPV_EBOR = "MESSAGE_C2LHPV_EBOR";
    static final String MESSAGE_STRONG_WIND_50 = "MESSAGE_STRONG_WIND_50";
    static final String MESSAGE_STRONG_WIND = "MESSAGE_STRONG_WIND";
    static final String LABEL_VISIBILITY = "LABEL_VISIBILITY";
    static final String LOWER_BOUND_NORMAL_VISIBILITY = "LOWER_BOUND_NORMAL_VISIBILITY";
    static final String LOWER_BOUND_DROPPING_VISIBILITY = "LOWER_BOUND_DROPPING_VISIBILITY";
    static final String LOWER_BOUND_REDUCE_VISIBILITY = "LOWER_BOUND_REDUCE_VISIBILITY";
    static final String LOWER_BOUND_REDUCE_VISIBILITY_50 = "LOWER_BOUND_REDUCE_VISIBILITY_50";
    static final String LOWER_BOUND_REDUCE_VISIBILITY_35 = "LOWER_BOUND_REDUCE_VISIBILITY_35";
    static final String MESSAGE_DROPPING_VISIBILITY = "MESSAGE_DROPPING_VISIBILITY";
    static final String MESSAGE_REDUCE_VISIBILITY = "MESSAGE_REDUCE_VISIBILITY";
    static final String MESSAGE_REDUCE_VISIBILITY_50 = "MESSAGE_REDUCE_VISIBILITY_50";
    static final String MESSAGE_REDUCE_VISIBILITY_35 = "MESSAGE_REDUCE_VISIBILITY_35";
    private static final String DEFAULT_LABEL_GUST = "WINDSPEED_GUST";
    private static final String DEFAULT_LOWER_BOUND_C2LHPV_EBOR = "60";
    private static final String DEFAULT_LOWER_BOUND_STRONG_WIND_50 = "50";
    private static final String DEFAULT_LOWER_BOUND_STRONG_WIND = "40";
    private static final String DEFAULT_MESSAGE_C2LHPV_EBOR = "RWIS reports C2LHPV or EBOR";
    private static final String DEFAULT_MESSAGE_STRONG_WIND_50 = "RWIS reports Strong wind 50";
    private static final String DEFAULT_MESSAGE_STRONG_WIND = "RWIS reports Strong wind";
    private static final String DEFAULT_LABEL_VISIBILITY = "VISIBILITY";
    private static final String DEFAULT_LOWER_BOUND_NORMAL_VISIBILITY = "1000";
    private static final String DEFAULT_LOWER_BOUND_DROPPING_VISIBILITY = "420";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY = "290";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_50 = "170";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_35 = "170";
    private static final String DEFAULT_MESSAGE_DROPPING_VISIBILITY = "RWIS reports DROPPING_VISIBILITY";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY = "RWIS reports REDUCE_VISIBILITY";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY_50 = "RWIS reports REDUCE_VISIBILITY_50";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY_35 = "RWIS reports REDUCE_VISIBILITY_35";


    public static void initializeTableConditionsData() {
        properties.put(LABEL_GUST, DEFAULT_LABEL_GUST);

        properties.put(LOWER_BOUND_C2LHPV_EBOR, DEFAULT_LOWER_BOUND_C2LHPV_EBOR);
        properties.put(LOWER_BOUND_STRONG_WIND_50, DEFAULT_LOWER_BOUND_STRONG_WIND_50);
        properties.put(LOWER_BOUND_STRONG_WIND, DEFAULT_LOWER_BOUND_STRONG_WIND);

        properties.put(MESSAGE_C2LHPV_EBOR,DEFAULT_MESSAGE_C2LHPV_EBOR);
        properties.put(MESSAGE_STRONG_WIND_50,DEFAULT_MESSAGE_STRONG_WIND_50);
        properties.put(MESSAGE_STRONG_WIND,DEFAULT_MESSAGE_STRONG_WIND);

        properties.put(LABEL_VISIBILITY, DEFAULT_LABEL_VISIBILITY);

        properties.put(LOWER_BOUND_NORMAL_VISIBILITY, DEFAULT_LOWER_BOUND_NORMAL_VISIBILITY);
        properties.put(LOWER_BOUND_DROPPING_VISIBILITY, DEFAULT_LOWER_BOUND_DROPPING_VISIBILITY);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY_50, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_50);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY_35, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_35);

        properties.put(MESSAGE_DROPPING_VISIBILITY, DEFAULT_MESSAGE_DROPPING_VISIBILITY);
        properties.put(MESSAGE_REDUCE_VISIBILITY, DEFAULT_MESSAGE_REDUCE_VISIBILITY);
        properties.put(MESSAGE_REDUCE_VISIBILITY_50, DEFAULT_MESSAGE_REDUCE_VISIBILITY_50);
        properties.put(MESSAGE_REDUCE_VISIBILITY_35, DEFAULT_MESSAGE_REDUCE_VISIBILITY_35);
    }
}
