package ro.pahotech.rwid.tableConditions;

import static ro.pahotech.rwid.Data.properties;

public class TableConditionsData {
    static final String LABEL_GUST = "LABEL_GUST";
    static final String LOWER_BOUND_C2LHPV_EBOR = "LOWER_BOUND_C2LHPV_EBOR";
    static final String LOWER_BOUND_STRONG_WIND_50 = "LOWER_BOUND_STRONG_WIND_50";
    static final String LOWER_BOUND_STRONG_WIND = "LOWER_BOUND_STRONG_WIND";
    static final String MESSAGE_C2LHPV_EBOR = "MESSAGE_C2LHPV_EBOR";
    static final String MESSAGE_STRONG_WIND_50 = "MESSAGE_STRONG_WIND_50";
    static final String MESSAGE_STRONG_WIND = "MESSAGE_STRONG_WIND";
    static final String LABEL_VISIBILITY = "LABEL_VISIBILITY";
    static final String LOWER_BOUND_NORMAL_VISIBILITY = "LOWER_BOUND_NORMAL_VISIBILITY";
    static final String LOWER_BOUND_DROPPING_VISIBILITY = "LOWER_BOUND_DROPPING_VISIBILITY";
    static final String LOWER_BOUND_REDUCE_VISIBILITY = "LOWER_BOUND_REDUCE_VISIBILITY";
    static final String LOWER_BOUND_REDUCE_VISIBILITY_50 = "LOWER_BOUND_REDUCE_VISIBILITY_50";
    static final String LOWER_BOUND_REDUCE_VISIBILITY_35 = "LOWER_BOUND_REDUCE_VISIBILITY_35";
    static final String MESSAGE_DROPPING_VISIBILITY = "MESSAGE_DROPPING_VISIBILITY";
    static final String MESSAGE_REDUCE_VISIBILITY = "MESSAGE_REDUCE_VISIBILITY";
    static final String MESSAGE_REDUCE_VISIBILITY_50 = "MESSAGE_REDUCE_VISIBILITY_50";
    static final String MESSAGE_REDUCE_VISIBILITY_35 = "MESSAGE_REDUCE_VISIBILITY_35";
    private static final String DEFAULT_LABEL_GUST = "WINDSPEED_GUST";
    private static final String DEFAULT_LOWER_BOUND_C2LHPV_EBOR = "60";
    private static final String DEFAULT_LOWER_BOUND_STRONG_WIND_50 = "50";
    private static final String DEFAULT_LOWER_BOUND_STRONG_WIND = "40";
    static final String MESSAGE_STRONG_WIND_ALERT_DROP = "MESSAGE_STRONG_WIND_ALERT_DROP";
    static final String COUNTER_C2LHPV_EBOR_FINISH_LIMIT = "COUNTER_C2LHPV_EBOR_FINISH_LIMIT";
    private static final String DEFAULT_MESSAGE_C2LHPV_EBOR = "RWIS Checker reports C2LHPV or EBOR";
    private static final String DEFAULT_LABEL_VISIBILITY = "VISIBILITY";
    private static final String DEFAULT_LOWER_BOUND_NORMAL_VISIBILITY = "1000";
    private static final String DEFAULT_LOWER_BOUND_DROPPING_VISIBILITY = "420";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY = "290";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_50 = "170";
    private static final String DEFAULT_MESSAGE_STRONG_WIND_50 = "RWIS Checker reports STRONG WIND 50";
    private static final String DEFAULT_MESSAGE_STRONG_WIND = "RWIS Checker reports SRRONG WIND";
    private static final String DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_35 = "0";
    private static final String DEFAULT_MESSAGE_DROPPING_VISIBILITY = "RWIS Checker reports DROPPING VISIBILITY";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY = "RWIS Checker reports REDUCE VISIBILITY";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY_50 = "RWIS Checker reports REDUCE VISIBILITY 50";
    private static final String DEFAULT_MESSAGE_REDUCE_VISIBILITY_35 = "RWIS Checker reports REDUCE VISIBILITY 35";
    private static final String DEFAULT_MESSAGE_STRONG_WIND_ALERT_DROP = "Strong wind alert has been dropped!";
    private static final String DEFAULT_COUNTER_C2LHPV_EBOR_FINISH_LIMIT = "6";

    public static void initializeTableConditionsData() {
        properties.put(LABEL_GUST, DEFAULT_LABEL_GUST);

        properties.put(LOWER_BOUND_C2LHPV_EBOR, DEFAULT_LOWER_BOUND_C2LHPV_EBOR);
        properties.put(LOWER_BOUND_STRONG_WIND_50, DEFAULT_LOWER_BOUND_STRONG_WIND_50);
        properties.put(LOWER_BOUND_STRONG_WIND, DEFAULT_LOWER_BOUND_STRONG_WIND);

        properties.put(MESSAGE_STRONG_WIND_ALERT_DROP, DEFAULT_MESSAGE_STRONG_WIND_ALERT_DROP);

        properties.put(MESSAGE_C2LHPV_EBOR,DEFAULT_MESSAGE_C2LHPV_EBOR);
        properties.put(MESSAGE_STRONG_WIND_50,DEFAULT_MESSAGE_STRONG_WIND_50);
        properties.put(MESSAGE_STRONG_WIND,DEFAULT_MESSAGE_STRONG_WIND);

        properties.put(COUNTER_C2LHPV_EBOR_FINISH_LIMIT, DEFAULT_COUNTER_C2LHPV_EBOR_FINISH_LIMIT);

        properties.put(LABEL_VISIBILITY, DEFAULT_LABEL_VISIBILITY);

        properties.put(LOWER_BOUND_NORMAL_VISIBILITY, DEFAULT_LOWER_BOUND_NORMAL_VISIBILITY);
        properties.put(LOWER_BOUND_DROPPING_VISIBILITY, DEFAULT_LOWER_BOUND_DROPPING_VISIBILITY);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY_50, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_50);
        properties.put(LOWER_BOUND_REDUCE_VISIBILITY_35, DEFAULT_LOWER_BOUND_REDUCE_VISIBILITY_35);

        properties.put(MESSAGE_DROPPING_VISIBILITY, DEFAULT_MESSAGE_DROPPING_VISIBILITY);
        properties.put(MESSAGE_REDUCE_VISIBILITY, DEFAULT_MESSAGE_REDUCE_VISIBILITY);
        properties.put(MESSAGE_REDUCE_VISIBILITY_50, DEFAULT_MESSAGE_REDUCE_VISIBILITY_50);
        properties.put(MESSAGE_REDUCE_VISIBILITY_35, DEFAULT_MESSAGE_REDUCE_VISIBILITY_35);
    }
}
